name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install rpm
      run: |
        sudo apt update
        sudo apt install rpm
    - name: Run packaging
      run: |
        rpmbuild --define "_sourcedir `pwd`" --bb rpi3_wifi_firmware.spec -v
