name: release

on: 
  release: 
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install rpm 
      run: |
        sudo apt update
        sudo apt install rpm 
    - name: Packaging
      run: |
        rpmbuild --define "_sourcedir `pwd`" --bb rpi3_wifi_firmware.spec -v
    - name : Install ghr
       run: |
         export GOPATH=${HOME}/go 
         mkdir -p ${GOPATH}
         go get -u github.com/tcnksm/ghr
         echo "GOPATH : ${GOPATH}"
    - name : Upload release
      run: |
        export GOPATH=${HOME}/go
        export GOPATH_BIN=${GOPATH}/bin
        echo "user : ${GITHUB_REPOSITORY%/*}"
        echo "repo : ${GITHUB_REPOSITORY#*/}"
        echo "tag : ${GITHUB_REF#refs/tags/}"
        $GOPATH_BIN/ghr -t "${GITHUB_TOKEN}" -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" "${GITHUB_REF#refs/tags/}" "/home/runner/rpmbuild/RPMS/noarch/"
