name: release

on: 
  release: 
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install rpm 
      run: |
        sudo apt update
        sudo apt install rpm 
    - name: Run packaging
      run: |
        rpmbuild --define "_sourcedir `pwd`" --bb rpi3_wifi_firmware.spec -v
    - name : Upload release
      run: |
        mkdir -p /home/runner/go
        export GOPATH="/home/runner/go"
        go get -u github.com/tcnksm/ghr
        echo "GITHUB_REF : ${GITHUB_REF}"
        echo "GITHUB_REF#refs/tags/: ${GITHUB_REF#refs/tags/}"
        $GOPATH/bin/ghr -t ${GITHUB_TOKEN} -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" "${GITHUB_REF}" "/home/runner/rpmbuild/RPMS/noarch/"
